<a href="https://colab.research.google.com/github/PAM-cake/DA-ML_practice./blob/main/FEATURE_EXTRACTION_PRACTICE_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import re
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [ ]:
dataset = pd.read_csv('/content/Placement_Dataset.csv')

In [ ]:
dataset.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [ ]:
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(dataset['status'])
dataset['p_or_n'] = labels

In [ ]:
dataset.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,p_or_n,content
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,1,270000.0,LabelEncoder(),1 Sci&Tech
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,1,200000.0,LabelEncoder(),1 Sci&Tech
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,1,250000.0,LabelEncoder(),1 Comm&Mgmt
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,0,NaN,LabelEncoder(),0 Sci&Tech
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,1,425000.0,LabelEncoder(),1 Comm&Mgmt

In [ ]:
dataset['content'] = dataset["p_or_n"]+" "+dataset['degree_t']

In [ ]:
print(dataset)

     sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00
1        2      M  79.33  Central  78.33   Others   Science     77.48
2        3      M  65.00  Central  68.00  Central      Arts     64.00
3        4      M  56.00  Central  52.00  Central   Science     52.00
4        5      M  85.80  Central  73.60  Central  Commerce     73.30
..     ...    ...    ...      ...    ...      ...       ...       ...
210    211      M  80.60   Others  82.00   Others  Commerce     77.60
211    212      M  58.00   Others  60.00   Others   Science     72.00
212    213      M  67.00   Others  67.00   Others  Commerce     73.00
213    214      F  74.00   Others  66.00   Others  Commerce     58.00
214    215      M  62.00  Central  58.00   Others   Science     53.00

      degree_t workex  etest_p specialisation  mba_p  status    salary  \
0     Sci&Tech     No     55.0         Mkt&HR  58.80       1  270000.0
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28       1  200000.0
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80       1  250000.0
3     Sci&Tech     No     66.0         Mkt&HR  59.43       0       NaN
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50       1  425000.0
..         ...    ...      ...            ...    ...     ...       ...
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49       1  400000.0
211   Sci&Tech     No     74.0        Mkt&Fin  53.62       1  275000.0
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72       1  295000.0
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23       1  204000.0
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22       0       NaN

     p_or_n      content
0         1   1 Sci&Tech
1         1   1 Sci&Tech
2         1  1 Comm&Mgmt
3         0   0 Sci&Tech
4         1  1 Comm&Mgmt
..      ...          ...
210       1  1 Comm&Mgmt
211       1   1 Sci&Tech
212       1  1 Comm&Mgmt
213       1  1 Comm&Mgmt
214       0  0 Comm&Mgmt

[215 rows x 17 columns]

In [ ]:
X = dataset['content'].values
y = dataset['p_or_n'].values

In [ ]:
vectorizer = TfidfVectorizer()
vectorizer.fit(X)
X = vectorizer.transform(X)

In [ ]:
print(X)

  (0, 3)	0.7071067811865475
  (0, 4)	0.7071067811865475
  (1, 3)	0.7071067811865475
  (1, 4)	0.7071067811865475
  (2, 0)	0.7071067811865476
  (2, 1)	0.7071067811865476
  (3, 3)	0.7071067811865475
  (3, 4)	0.7071067811865475
  (4, 0)	0.7071067811865476
  (4, 1)	0.7071067811865476
  (5, 3)	0.7071067811865475
  (5, 4)	0.7071067811865475
  (6, 0)	0.7071067811865476
  (6, 1)	0.7071067811865476
  (7, 3)	0.7071067811865475
  (7, 4)	0.7071067811865475
  (8, 0)	0.7071067811865476
  (8, 1)	0.7071067811865476
  (9, 0)	0.7071067811865476
  (9, 1)	0.7071067811865476
  (10, 0)	0.7071067811865476
  (10, 1)	0.7071067811865476
  (11, 0)	0.7071067811865476
  (11, 1)	0.7071067811865476
  (12, 0)	0.7071067811865476
  :	:
  (202, 4)	0.7071067811865475
  (203, 0)	0.7071067811865476
  (203, 1)	0.7071067811865476
  (204, 0)	0.7071067811865476
  (204, 1)	0.7071067811865476
  (205, 0)	0.7071067811865476
  (205, 1)	0.7071067811865476
  (206, 0)	0.7071067811865476
  (206, 1)	0.7071067811865476
  (207, 0)	0.7071067811865476
  (207, 1)	0.7071067811865476
  (208, 0)	0.7071067811865476
  (208, 1)	0.7071067811865476
  (209, 0)	0.7071067811865476
  (209, 1)	0.7071067811865476
  (210, 0)	0.7071067811865476
  (210, 1)	0.7071067811865476
  (211, 3)	0.7071067811865475
  (211, 4)	0.7071067811865475
  (212, 0)	0.7071067811865476
  (212, 1)	0.7071067811865476
  (213, 0)	0.7071067811865476
  (213, 1)	0.7071067811865476
  (214, 0)	0.7071067811865476
  (214, 1)	0.7071067811865476